name: Download and Commit Files

on:
  push:
    branches:
      - main

jobs:
  download:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout repository
        uses: actions/checkout@v4

      - name: Download files
        run: |
          content="$(cat urls.txt)"
          mkdir -p downloaded_files
          cd downloaded_files
          while IFS= read -r url; do
            curl -O "$url"
          done <<< "$content"

      - name: Archive downloaded files
        uses: actions/upload-artifact@v4
        with:
          name: downloaded-files  # Nom de l'artefact
          path: downloaded_files   # Chemin vers les fichiers téléchargés

      - name: Rename and commit files
        run: |
          # Récupérer les fichiers téléchargés de l'artefact
          mkdir renamed_files
          cd renamed_files
          # Télécharger les fichiers de l'artefact
          wget -O downloaded_files.zip "${{ steps.archive.outputs.artifact_url }}"
          # Extraire les fichiers
          unzip downloaded_files.zip
          # Renommer les fichiers avec le format spécifié
          for file in *; do
            new_name="file_$(date '+%Y%m%d_%H%M%S')_${file}"
            mv "$file" "$new_name"
          done
          # Ajouter, commettre et pousser les fichiers renommés
          git config --global user.email "actions@github.com"
          git config --global user.name "GitHub Actions"
          git add .
          git commit -m "Add renamed files"
          git push
