name: Download and Commit Files

on: [push]

    

jobs:
  download_and_commit:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout repository
        uses: actions/checkout@v4

      - name: Install curl and git
        run: |
          sudo apt update
          sudo apt install -y curl git

      - name: Download files from URLs
        env:
            CONTENT: $(cat "urls.txt")
        run: |
          echo "$CONTENT"
          echo "good"
         

      - name: Add and commit downloaded files
        run: |
          git config --global user.email "actions@github.com"
          git config --global user.name "GitHub Actions"
          git add .
          git commit -m "Add downloaded files"
          git push 