name: Download and Commit Files 

on: [push]

    

jobs:
  download:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout repository
        uses: actions/checkout@v4

      - name: Create directory for downloaded files if not exists
        run: |
          if [ ! -d downloaded_files ]; then
            mkdir downloaded_files
          fi

      - name: Read URLs from file
        id: read-urls
        run: |
          content=$(<urls.txt)

      - name: Download files
        run: |
          content="${{ steps.read-urls.outputs.urls }}"
          mkdir downloaded_files
          cd downloaded_files
          while IFS= read -r url; do
            curl -O "$url"
          done <<< "$content"
         

      - name: Add and commit downloaded files
        run: |
          git config --global user.email "actions@github.com"
          git config --global user.name "GitHub Actions"
          git add .
          git commit -m "Add downloaded files"
          git push 
