name: Download and Commit Files 

on: [push]

    

jobs:
  download:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout repository
        uses: actions/checkout@v4

      - name: Download files
        run: |
          content="$(cat urls.txt)"
          mkdir -p downloaded_files
          cd downloaded_files
          while IFS= read -r url; do
          filename="$(basename "$url")" 
          timestamp=$(date +%Y-%m-%dT%H-%M-%S) 
            curl -O "$timestamp-$filename" "$url"
          done <<< "$content"
      
      - name: Upload artifacts
        uses: actions/upload-artifact@v4
        with:
          name: downloaded-files
          path: downloaded_files/
         

  commit-downloaded-files:
    needs: download  
    runs-on: ubuntu-latest

    steps:
      - name: Download artifacts
        uses: actions/download-artifact@v4
        with:
          name: downloaded-files

      - name: Add and commit downloaded files (replace with your credentials)
        run: |
          git config --global user.email "your_github_email@example.com"
          git config --global user.name "Your GitHub Username"

          git add downloaded-files/*
          git commit -m "Add downloaded files with timestamps (YYYY-MM-DDTHH-MM-SS)"
          git push