name: Download and Commit Files

on: [push]

    

jobs:
  download:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout repository
        uses: actions/checkout@v4

      - name: Read URLs from file
        id: read-urls
        run: |
          content=$(<urls.txt)
          echo "::set-output name=urls::$content"

      - name: Download files
        run: |
          content="${{ steps.read-urls.outputs.urls }}"
          while IFS= read -r url; do
            wget "$url"
          done <<< "$content"
         

      - name: Add and commit downloaded files
        run: |
          git config --global user.email "actions@github.com"
          git config --global user.name "GitHub Actions"
          git add .
          git commit -m "Add downloaded files"
          git push 