name: Download and Commit Files 

on: [push]

    

jobs:
  download:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout repository
        uses: actions/checkout@v4

      - name: Download files
        run: |
          content="$(cat urls.txt)"
          mkdir -p downloaded_files
          cd downloaded_files
          while IFS= read -r url; do
            curl -O "$url"
          done <<< "$content"
      
      - name: Upload artifacts
        uses: actions/upload-artifact@v4
        with:
          name: downloaded-files
          path: downloaded_files/
      
      - name: Download artifacts
        uses: actions/download-artifact@v4
        with:
            name: downloaded-files
            path: downloaded_files/
      
      - name: Rename files
        run: |
          cd downloaded_files/
          for file in *; do
            filename=$(basename "$file")
            timestamp=$(date +%Y-%m-%d-%H-%M-%S)
            new_filename="file-$timestamp"
            mv "$file" "$new_filename"
          done

      - name: Add and commit downloaded files 
        run: |
          git config --global user.email "actions@github.com"
          git config --global user.name "GitHub Actions"

          git add .
          git commit -m "Add downloaded files with timestamps (YYYY-MM-DDTHH-MM-SS)"
          git push
         

  